// +build generate
//go:generate go run $GOFILE

package main

import "os"
import "gopkg.in/yaml.v2"
import "text/template"
import "io/ioutil"
import "strings"
import "bytes"

func snakeToUpperCamel(word string) string {
	var buffer bytes.Buffer

	capitalize := true
	for i := 0; i < len(word); i++ {
		if word[i] == '_' {
			capitalize = true
			continue
		}
		if capitalize {
			ch := strings.ToUpper(string(word[i]))
			buffer.WriteString(ch)
			capitalize = false
		} else {
			buffer.WriteString(string(word[i]))
			capitalize = false
		}
	}

	return buffer.String()
}

func loadConfig() map[interface{}]interface{} {
	config, err := ioutil.ReadFile("$generate.yml")
	if err != nil {
		panic(err)
	}

	m := make(map[interface{}]interface{})
	err = yaml.Unmarshal(config, &m)
	if err != nil {
		panic(err)
	}
	return m
}

func main() {
	config := loadConfig()

	cwd, err := os.Open(".")
	if err != nil {
		panic(err)
	}
	defer cwd.Close()

	files, err := cwd.Readdir(-1)
	if err != nil {
		panic(err)
	}

	for _, file := range files {
		fname := file.Name()
		if !strings.HasSuffix(fname, ".go.in") {
			continue
		}

		in, err := ioutil.ReadFile(fname)
		if err != nil {
			panic(err)
		}

		t := template.Must(template.New("$generate").Funcs(template.FuncMap{
			"snakeToUpperCamel": snakeToUpperCamel,
		}).Parse(string(in)))

		out, err := os.Create(fname[:len(fname)-3])
		if err != nil {
			panic(err)
		}
		defer out.Close()

		out.WriteString("// DO NOT EDIT THIS FILE\n")
		out.WriteString("// This file is generated from " + fname + "\n")
		out.WriteString("\n")

		if err = t.Execute(out, config); err != nil {
			panic(err)
		}
	}
}
